[project]
name = "agno-agent"
version = "0.1.0"
description = "An AI agent using Agno framework with Claude and YFinance tools"
requires-python = ">=3.12"
dependencies = [
    "agno>=1.5.10",
    "openai>=1.84.0",
    "yfinance>=0.2.61",
]
